
DROP TABLE IF EXISTS `order_main`;
CREATE TABLE `order_main` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_no` varchar(32) NOT NULL COMMENT '订单编号（唯一，格式：ORD+yyyyMMdd+12位数字）',
    `plate_number` varchar(16) NOT NULL COMMENT '车牌号',
    `parking_lot_id` bigint NOT NULL COMMENT '停车场ID',
    `parking_lot_name` varchar(64) NOT NULL COMMENT '停车场名称',
    `enter_time` datetime NOT NULL COMMENT '入场时间',
    `exit_time` datetime DEFAULT NULL COMMENT '出场时间',
    `original_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '原始费用',
    `discount_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '优惠金额',
    `coupon_id` bigint DEFAULT NULL COMMENT '使用的优惠券ID',
    `coupon_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '优惠券抵扣金额',
    `final_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '最终支付金额',
    `payment_method` varchar(16) DEFAULT NULL COMMENT '支付方式：wechat/alipay/balance/gift',
    `payment_status` tinyint NOT NULL DEFAULT 0 COMMENT '支付状态：0待支付 1支付中 2已支付 3支付失败 4已退款',
    `order_status` tinyint NOT NULL DEFAULT 0 COMMENT '订单状态：0待支付 1已支付 2已取消 3已完成 4已退款',
    `user_id` bigint DEFAULT NULL COMMENT '用户ID（可为空，临时用户）',
    `vehicle_id` bigint DEFAULT NULL COMMENT '车辆ID（可为空）',
    `monthly_card_id` bigint DEFAULT NULL COMMENT '使用的月卡ID（月卡用户）',
    `is_monthly_card` tinyint NOT NULL DEFAULT 0 COMMENT '是否月卡支付：0否 1是',
    `enter_channel` varchar(32) DEFAULT NULL COMMENT '入场渠道：camera/scan/manual',
    `exit_channel` varchar(32) DEFAULT NULL COMMENT '出场渠道：camera/scan/manual',
    `remark` varchar(255) DEFAULT NULL COMMENT '备注',
    `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_plate_number` (`plate_number`),
    KEY `idx_parking_lot_id` (`parking_lot_id`),
    KEY `idx_order_status` (`order_status`),
    KEY `idx_payment_status` (`payment_status`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_enter_time` (`enter_time`),
    KEY `idx_exit_time` (`exit_time`),
    KEY `idx_gmt_create` (`gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='订单统计月报表';